# Generated by Django 4.2.3 on 2024-02-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_article_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="rating",
            field=models.FloatField(default=0),
        ),
    ]
