# Generated by Django 4.2.3 on 2024-02-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_article_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="article_image",
            field=models.ImageField(blank=True, null=True, upload_to="articles/images"),
        ),
    ]
