# Generated by Django 4.2.3 on 2024-02-26 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_article_article_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="rating",
        ),
        migrations.AddField(
            model_name="comment",
            name="rating",
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
